name: bubbly
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: '>=2.15.0 <3.19.6'

dependency_overrides:
  video_player_android: 2.7.1

dependencies:
  flutter:
    sdk: flutter

  bubbly_camera:
    path: "CameraPlugin/camera"

  cupertino_icons: ^1.0.8

  #_______________ In App Purchase ___________________#
  in_app_purchase: ^3.2.0

  #_______________ Firebase,Notification,Ads ___________________#
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  google_mobile_ads: ^5.2.0

  #_______________ Sign in ___________________#
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  crypto: ^3.0.6

  #_______________ Functionality ___________________#

  http: ^1.2.2
  shimmer: ^3.0.0
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.6
  ffmpeg_kit_flutter_full: ^6.0.3
  url_launcher: ^6.3.1
  intl: ^0.19.0
  dio: ^5.7.0
  saver_gallery: ^3.0.10
  shared_preferences: ^2.3.2
  webview_flutter: ^4.9.0
  flutter_branch_sdk: ^8.2.0
  share_plus: ^10.1.0
  audioplayers: ^6.1.0
  audioplayers_darwin: ^6.0.0
  video_player: ^2.8.7

  #----------------- UI -----------------#
  screenshot: ^3.0.0
  fluttertoast: ^8.2.8
  device_info_plus: ^11.1.0
  visibility_detector: ^0.4.0+2
  wakelock_plus: ^1.2.8
  flutter_staggered_grid_view: ^0.7.0
  detectable_text_field: ^3.0.2
  bouncing_widget: ^2.0.0


  #----------------- Image,Files,Permission -----------------#

  path_provider: ^2.1.4
  flutter_downloader: ^1.11.8
  image_picker: ^1.1.2
  flutter_video_info: ^1.3.2
  permission_handler: ^11.3.1
  collection: ^1.18.0
  video_thumbnail: ^0.5.3
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  logger: ^2.4.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  path: ^1.9.0

  #----------------- Live Stream -----------------#
  agora_rtc_engine: ^6.3.2

  #----------------- State Management -----------------#
  stacked: ^3.4.3
  provider: ^6.1.2
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^9.1.3
  build_runner: ^2.4.13

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - icons/

  fonts:
    - family: SfUiBold
      fonts:
        - asset: font/SFUIDisplayBold.otf
    - family: SfUiLight
      fonts:
        - asset: font/SFUIDisplayLight.otf
    - family: SfUiMedium
      fonts:
        - asset: font/SFUIDisplayMedium.otf
    - family: SfUiHeavy
      fonts:
        - asset: font/SFUIDisplayHeavy.otf
    - family: SfUiRegular
      fonts:
        - asset: font/SFUIDisplayRegular.otf
    - family: SfUiSemiBold
      fonts:
        - asset: font/SFUIDisplaySemibold.otf

